"""
Django settings for eos_pro project.

Generated by 'django-admin startproject' using Django 6.0.
"""

import os # os 모듈은 경로 정의에 필수
from pathlib import Path

# 💡 [핵심 수정 1] BASE_DIR 정의를 os.path를 사용하는 절대 경로(str 타입)로 명확하게 변경
# settings.py가 있는 위치에서 2단계 위(.. / ..)인 프로젝트 루트를 가리킵니다.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v4-&y$q67lbhz-0kb1pbq8#03c%v3@v^4=e)5^%uc%$c6(*ks!'

# [수정 1] 보안을 위해 디버그 모드 끄기 (배포 시 필수!)
# **주의: 현재 개발 단계에서는 True로 바꾸는 것이 오류 추적에 유리합니다.**
DEBUG = True # 💡 배포 단계에서 잠시 True로 변경하여 오류 추적 용이하게 함

# [수정 2] EC2 Public IP 및 모든 도메인 접속 허용
ALLOWED_HOSTS = ['*', '13.125.15.15'] # 💡 EC2 IP 주소 추가


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'common',
    'django.contrib.humanize', # intcomma 필터 사용을 위해 추가
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'eos_pro.urls'

# 💡 [핵심 수정 2] TEMPLATES 경로: os.path.join으로 통일하여 Type Error 해결
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # 💡 Type Error 해결
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eos_pro.wsgi.application'


# Database
# 💡 [핵심 수정 3] DATABASES: 키를 소문자 'name'으로, 값은 os.path.join으로 변경
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'name': os.path.join(BASE_DIR, 'db.sqlite3'), # 💡 소문자 'name' 및 os.path.join 사용
    }
}


# Password validation
# ...

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# ...

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# ...

STATIC_URL = '/static/'

# 💡 [핵심 수정 4] STATIC_ROOT: os.path.join으로 통일하여 Type Error 해결
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 로그인/로그아웃 후 이동할 경로
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'