# Generated by Django 6.0 on 2025-12-10 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='행사명')),
                ('date', models.DateField(verbose_name='행사일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('general', '일반 행사 (General)'), ('conference', '컨퍼런스/세미나 (Conference)'), ('concert', '공연/콘서트 (Concert)'), ('exhibition', '전시회 (Exhibition)'), ('festival', '축제/이벤트 (Festival)')], default='general', max_length=20, verbose_name='행사 종류')),
                ('has_stage', models.BooleanField(default=False, verbose_name='[장비] 무대 하드웨어')),
                ('has_sound', models.BooleanField(default=False, verbose_name='[장비] 음향 시스템')),
                ('has_lighting', models.BooleanField(default=False, verbose_name='[장비] 조명 시스템')),
                ('has_screen', models.BooleanField(default=False, verbose_name='[장비] 영상/중계')),
                ('has_booth', models.BooleanField(default=False, verbose_name='[시설] 전시 부스')),
                ('has_print', models.BooleanField(default=False, verbose_name='[제작] 인쇄/홍보물')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('content', models.CharField(max_length=500)),
                ('duration', models.IntegerField(default=0)),
                ('bgm', models.CharField(blank=True, max_length=200)),
                ('action', models.CharField(default='Play', max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
            ],
        ),
    ]
