# Generated by Django 6.0 on 2025-12-10 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='할 일 내용')),
                ('deadline', models.DateField(verbose_name='마감일')),
                ('is_done', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='main.event')),
            ],
        ),
    ]
