# Generated by Django 6.0 on 2025-12-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='stage_depth',
            field=models.FloatField(default=0, verbose_name='무대 깊이(m)'),
        ),
        migrations.AddField(
            model_name='event',
            name='stage_height',
            field=models.FloatField(default=0, verbose_name='무대 높이(m)'),
        ),
        migrations.AddField(
            model_name='event',
            name='stage_width',
            field=models.FloatField(default=0, verbose_name='무대 가로(m)'),
        ),
    ]
