# Generated by Django 6.0 on 2025-12-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_event_stage_depth_event_stage_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_foh',
            field=models.BooleanField(default=True, verbose_name='FOH(콘솔) 배치'),
        ),
        migrations.AddField(
            model_name='event',
            name='has_virgin_road',
            field=models.BooleanField(default=False, verbose_name='버진로드 포함'),
        ),
        migrations.AddField(
            model_name='event',
            name='table_gap',
            field=models.FloatField(default=3.0, verbose_name='객석 간격(m)'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_depth',
            field=models.FloatField(default=40.0, verbose_name='공간 깊이(m)'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_height',
            field=models.FloatField(default=5.0, verbose_name='천고(m)'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_width',
            field=models.FloatField(default=20.0, verbose_name='공간 가로(m)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('speech', '기업행사/세미나 (Speech)'), ('performance', '공연/이벤트 (Performance)')], default='speech', max_length=20, verbose_name='행사 유형'),
        ),
        migrations.AlterField(
            model_name='event',
            name='has_lighting',
            field=models.BooleanField(default=True, verbose_name='[장비] 조명 사용'),
        ),
        migrations.AlterField(
            model_name='event',
            name='has_print',
            field=models.BooleanField(default=False, verbose_name='[제작] 인쇄물'),
        ),
        migrations.AlterField(
            model_name='event',
            name='has_screen',
            field=models.BooleanField(default=False, verbose_name='[장비] 영상 사용'),
        ),
        migrations.AlterField(
            model_name='event',
            name='has_sound',
            field=models.BooleanField(default=True, verbose_name='[장비] 음향 사용'),
        ),
        migrations.AlterField(
            model_name='event',
            name='has_stage',
            field=models.BooleanField(default=True, verbose_name='[장비] 무대 사용'),
        ),
        migrations.AlterField(
            model_name='event',
            name='stage_depth',
            field=models.FloatField(default=4.8, verbose_name='무대 깊이(m)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='stage_height',
            field=models.FloatField(default=0.9, verbose_name='무대 높이(m)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='stage_width',
            field=models.FloatField(default=14.4, verbose_name='무대 가로(m)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='프로젝트명'),
        ),
    ]
