# Generated by Django 6.0 on 2025-12-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_event_has_foh_event_has_virgin_road_event_table_gap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('general', '일반 행사 (General)'), ('conference', '컨퍼런스/세미나 (Conference)'), ('concert', '공연/콘서트 (Concert)'), ('exhibition', '전시회 (Exhibition)'), ('festival', '축제/이벤트 (Festival)')], default='general', max_length=20, verbose_name='행사 유형'),
        ),
    ]
