# Generated by Django 6.0 on 2025-12-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='seating_type',
            field=models.CharField(choices=[('banquet', '연회식 (Round Table)'), ('theater', '극장식 (Theater / Chairs only)'), ('classroom', '강의식 (Classroom / Table & Chair)')], default='banquet', max_length=20, verbose_name='객석 배치 유형'),
        ),
    ]
