# Generated by Django 6.0 on 2025-12-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_event_seating_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='budget',
            field=models.IntegerField(default=0, verbose_name='총 예산(원)'),
        ),
        migrations.AddField(
            model_name='event',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='클라이언트(발주처)'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='장소명'),
        ),
    ]
