# Generated by Django 6.0 on 2025-12-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_event_budget_event_client_name_event_venue_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='expected_cost',
            field=models.IntegerField(default=0, verbose_name='예상 지출(비용)'),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('inquiry', '🟡 문의/접수'), ('design', '🔵 디자인/견적 중'), ('confirmed', '🟢 계약 확정 (준비 중)'), ('onsite', '🔴 현장 운영 중'), ('done', '⚪ 행사 종료')], default='inquiry', max_length=20, verbose_name='진행 상태'),
        ),
    ]
