# Generated by Django 6.0 on 2025-12-11 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_event_expected_cost_event_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='업체명')),
                ('business_number', models.CharField(max_length=20, unique=True, verbose_name='사업자등록번호')),
                ('contact_person', models.CharField(max_length=50, verbose_name='담당자')),
                ('phone_number', models.CharField(max_length=20, verbose_name='연락처')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='주소')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='actual_cost',
            field=models.IntegerField(default=0, verbose_name='실 지출(원)'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_external',
            field=models.BooleanField(default=False, verbose_name='외주 업무 여부'),
        ),
        migrations.AddField(
            model_name='task',
            name='planned_budget',
            field=models.IntegerField(default=0, verbose_name='책정 예산(원)'),
        ),
        migrations.AddField(
            model_name='task',
            name='po_status',
            field=models.CharField(choices=[('ready', '견적 요청 준비'), ('bidding', '입찰/견적 비교 중'), ('contracted', '계약 완료'), ('po_issued', '발주서 생성 완료')], default='ready', max_length=20, verbose_name='조달 상태'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_category',
            field=models.CharField(choices=[('admin', '행정/총무'), ('planning', '기획/콘텐츠'), ('execution', '실행/설치'), ('settlement', '정산/마감')], default='execution', max_length=20, verbose_name='업무 단계'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('exhibition', '1. 전시회 (Exhibition)'), ('event', '2. 이벤트/운영 (Event/Operation)'), ('conference', '3. 컨퍼런스/세미나 (Conference)'), ('ceremony', '4. 기념식/시상식 (Ceremony)'), ('festival', '5. 지역 축제 (Regional Festival)'), ('promotion', '6. 홍보/브랜딩 (Promotion)')], default='event', max_length=20, verbose_name='행사 유형'),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoted_amount', models.IntegerField(verbose_name='견적 금액(원)')),
                ('is_selected', models.BooleanField(default=False, verbose_name='선정 여부')),
                ('file', models.FileField(blank=True, null=True, upload_to='quotations/', verbose_name='견적 파일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task', verbose_name='관련 Task')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.vendor', verbose_name='제출 업체')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_amount', models.IntegerField(verbose_name='계약 금액(원)')),
                ('is_signed', models.BooleanField(default=False, verbose_name='전자 계약 완료')),
                ('po_date', models.DateField(auto_now_add=True, verbose_name='발주 일자')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task', verbose_name='관련 Task')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.vendor', verbose_name='계약 업체')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.vendor', verbose_name='담당 협력업체'),
        ),
    ]
