# Generated by Django 6.0 on 2025-12-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_vendor_task_actual_cost_task_is_external_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', '낮음'), ('MEDIUM', '보통'), ('HIGH', '높음')], default='MEDIUM', max_length=10, verbose_name='우선순위'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('GENERAL', '일반 업무'), ('PROCUREMENT', '발주/외주'), ('CHECKLIST', '점검/체크리스트')], default='GENERAL', max_length=20, verbose_name='Task 유형'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_category',
            field=models.CharField(choices=[('PLANNING', '기획'), ('DESIGN', '디자인'), ('PREPARATION', '제작/준비'), ('EXECUTION', '실행/현장'), ('CLOSING', '정산/마감')], default='PLANNING', max_length=20, verbose_name='Task 단계'),
        ),
    ]
